const D=window.KANSAI_DATA;
const ROUTE_COLOR={arrival:'#64748b',day1:'#111827',day2:'#334155',transfer:'#0f172a',osaka_conan:'#475569',food:'#9ca3af',return:'#94a3b8'};
const CATEGORY_EMOJI={pikmin:'🌱',jjk:'🌀',conan:'🕵️',literary:'📚',food:'🍜',hotel:'🏨'};
const CATEGORY_LABELS={all:'全部',pikmin:'Pikmin',jjk:'咒術迴戰',conan:'名偵探柯南',literary:'文學／自然',food:'餐廳／小吃',hotel:'飯店'};
const EXTRA={hotel_kyoto:{emoji:'🏨',site:'https://www.solarehotels.com/hotel/kyoto/loisir-kyototoji/',siteLabel:'飯店官網',highlights:['確認 check-in / 行李寄放與大浴場時間','先看京都站與東寺站的進出路線']},hotel_osaka:{emoji:'🏨',site:'https://www.hafh.com/en/properties/3150',siteLabel:'飯店資訊',highlights:['確認 check-in / 行李寄放與心齋橋站出口','回飯店後接道頓堀或機場線都方便']},kyoto_station:{emoji:'🚉',site:'https://www.kyoto-station-building.co.jp/en/',siteLabel:'官方網站',highlights:['適合抵達日晚間低強度散步','站內餐廳多，適合第一晚簡單收尾']},kyoto_tower:{emoji:'🗼',site:'https://www.kyoto-tower.jp/en/',siteLabel:'官方網站',highlights:['可與京都站綁同區段處理','若太晚到，不必硬上高處景點']},fushimi_inari:{emoji:'⛩️',site:'https://fushimiinari.jp/en/',siteLabel:'官方網站',highlights:['建議早點到，避開人潮最有感','千本鳥居段最值得拍，也最耗步行時間']},zuishinin:{emoji:'🌱',site:'https://www.zuishinin.or.jp/',siteLabel:'寺院官網',highlights:['山科段可作為 Pikmin 主點','結束後接地鐵回市中心效率高']},kiddy_land:{emoji:'🛍️',site:'https://www.kiddyland.co.jp/shoplist/kyoto/',siteLabel:'店鋪官網',highlights:['動漫周邊補貨點，建議預留購物時間','接錦市場與鴨川都很順']},yasaka_pagoda:{emoji:'🏯',site:'https://www.hokanji.com/',siteLabel:'寺院官網',highlights:['最適合拍京都街景經典畫面','可與八坂庚申堂合併停留']},yasaka_shrine:{emoji:'⛩️',site:'https://www.yasaka-jinja.or.jp/en/',siteLabel:'官方網站',highlights:['可與祇園、八坂塔一起安排','若時間不足可當成東山補點']},kiyomizu:{emoji:'🛕',site:'https://www.kiyomizudera.or.jp/en/',siteLabel:'官方網站',highlights:['上坡與人潮較明顯，要看體力決定是否加入','若只想保留京都街景感，未必一定要塞']},pontocho:{emoji:'🍶',site:'https://www.ponto-chou.com/en/',siteLabel:'街區官網',highlights:['適合晚餐後散步，不一定要白天排','先決定是用餐還是純散步']},nishiki:{emoji:'🍡',site:'https://www.kyoto-nishiki.or.jp/en/',siteLabel:'市場官網',highlights:['以補小吃和伴手禮為主，節奏不要太趕','建議停下來吃，不要邊走邊吃']},campo:{emoji:'🍽️',site:'https://campo-su-ovest.com/',siteLabel:'餐廳官網',highlights:['偏晚餐收尾型，不適合走很趕的日子','若要正式用餐，先看預約條件']},rakusai_bamboo:{emoji:'🎋',site:'https://chikurin-park.com/opening_en',siteLabel:'園區官網',highlights:['竹林段適合放慢節奏','比嵐山主竹林更有空間感']},jingoji:{emoji:'🍁',site:'https://jingoji.or.jp/',siteLabel:'寺院官網',highlights:['高雄段步行與階梯較多，要看鞋子與體力','很適合當自然山景收尾主點']},philosophers_path:{emoji:'🍃',site:'https://kyoto.travel/en/destinations/philosophers-path-tetsugakunomichi/',siteLabel:'京都觀光頁',highlights:['適合喜歡散步與留白的人','不建議和高強度跑點擠在同一時段']},monk:{emoji:'🍷',site:'https://restaurant-monk.com/',siteLabel:'餐廳官網',highlights:['通常要先處理預約','若吃 Monk，當天其他行程不要排太滿']},tsutenkaku:{emoji:'🗼',site:'https://www.tsutenkaku.co.jp/',siteLabel:'官方網站',highlights:['和新世界商店街可一起逛','若只想補大阪地標，停留可壓短']},osaka_castle:{emoji:'🏯',site:'https://www.osakacastle.net/',siteLabel:'官方網站',highlights:['範圍大，先決定是看外圍、天守閣還是公園','若天氣熱，要控制停留時間']},ytv:{emoji:'📺',site:'https://www.ytv.co.jp/10plaza/',siteLabel:'官方網站',highlights:['最適合柯南粉補官方感','可和大阪城安排同區段，不用拆開跑']}};
const DAY_SEQUENCE={arrival:[{id:'hotel_kyoto',move:'入住／放行李'},{id:'kyoto_station',move:'步行 12–15 分'},{id:'kyoto_tower',move:'步行 3–5 分'}],day1:[{id:'fushimi_inari',move:'JR＋步行 10–15 分'},{id:'gokonomiya',move:'電車／計程車 20–25 分'},{id:'zuishinin',move:'電車＋步行 25–35 分'},{id:'kamo_bridge',move:'地下鐵＋步行 25–30 分'},{id:'kiddy_land',move:'步行 5–8 分'},{id:'yasaka_pagoda',move:'步行／短程計程車 18–25 分'},{id:'yasaka_koshindo',move:'步行 3–5 分'},{id:'yasaka_shrine',move:'步行 8–10 分'},{id:'kiyomizu',move:'步行 12–15 分'},{id:'pontocho',move:'晚餐後散步'}],day2:[{id:'rakusai_bamboo',move:'飯店出發 40–50 分'},{id:'rakushisha',move:'巴士／計程車 20–25 分'},{id:'togetsukyo',move:'步行 15–20 分'},{id:'jingoji',move:'巴士／計程車 30–40 分'},{id:'philosophers_path',move:'可選延伸 15–20 分'},{id:'monk',move:'步行 5–8 分'}],transfer:[{id:'hotel_osaka',move:'京都→大阪換宿 70–90 分'},{id:'tsutenkaku',move:'地下鐵＋步行 20–25 分'},{id:'osaka_castle',move:'地下鐵＋步行 25–35 分'},{id:'ytv',move:'步行 18–25 分'}],osaka_conan:[{id:'tsutenkaku',move:'心齋橋出發 20–25 分'},{id:'osaka_castle',move:'地下鐵＋步行 25–35 分'},{id:'ytv',move:'步行 18–25 分'},{id:'hotel_osaka',move:'回飯店 25–30 分'}],return:[{id:'hotel_osaka',move:'早餐／退房'},{custom:true,emoji:'🛫',name:'關西機場 KIX',area:'返程',summary:'抓機場線與報到流程，建議預留 2.5–3 小時',move:'機場線移動'}]};
const byId=Object.fromEntries(D.points.map((p,i)=>[p.id,{...p,num:i+1}]));
const markerById={};
let currentView='all';
let currentCardType='all';
const style=document.createElement('style');
style.textContent=`.sequence-shell{display:grid;gap:12px}.sequence-panel{padding:14px;border:1px solid #e5e7eb;border-radius:16px;background:#fcfcfd}.sequence-panel-title{font-size:13px;font-weight:800;color:#111827;margin-bottom:6px}.sequence-panel-text{font-size:13px;line-height:1.7;color:#374151}.sequence-highlight-list{margin:0;padding-left:18px;color:#374151;line-height:1.7}.sequence-highlight-list li+li{margin-top:4px}.sequence-scroll{max-height:520px;overflow:auto;padding-right:6px}.sequence-scroll::-webkit-scrollbar{width:8px}.sequence-scroll::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:999px}.sequence-group{display:grid;gap:10px}.sequence-day{font-size:13px;font-weight:800;color:#6b7280}.sequence-item{padding:12px 14px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;transition:.15s ease}.sequence-item[data-spot-id]{cursor:pointer}.sequence-item[data-spot-id]:hover{transform:translateY(-1px);border-color:#cbd5e1;box-shadow:0 6px 16px rgba(15,23,42,.08)}.sequence-head{display:flex;gap:10px;align-items:flex-start}.sequence-emoji{width:34px;height:34px;border-radius:12px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:center;font-size:18px;flex:0 0 34px}.sequence-title{font-weight:800;line-height:1.4}.sequence-meta{font-size:13px;color:#6b7280;margin-top:2px}.sequence-summary{font-size:13px;line-height:1.6;color:#374151;margin-top:6px}.sequence-gap{display:flex;align-items:center;gap:8px;margin:0 10px 0 44px;color:#6b7280;font-size:12px}.sequence-gap:before{content:'↳';font-size:14px}.card-filter-bar{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 14px}.card-chip{border:1px solid #e5e7eb;background:#fff;border-radius:999px;padding:8px 12px;color:#111827;cursor:pointer}.card-chip.active{background:#111827;color:#fff;border-color:#111827}@media (max-width:960px){.sequence-scroll{max-height:420px}}`;
document.head.appendChild(style);
function getDefaultHighlights(p){return({pikmin:['確認是否有順利觸發 Pikmin 區域任務','看這點是否能順接下一區，不要單獨往返'],jjk:['拍照角度與人潮是主要體驗差異','先決定這裡是快拍補點還是慢慢逛'],conan:['若是聖地補點，停留不一定要很長','建議與同區段景點一起安排，效率最高'],literary:['節奏宜放慢，重點在氛圍不是打卡數量','看天氣與步行舒適度再決定停留長短'],food:['先確認營業時間、候位或預約規則','把用餐點放在順路區段，比特地繞路更舒服'],hotel:['看 check-in / 寄放行李 / 回程動線','把最近車站與機場移動時間先抓好']})[p.p]||['先確認當天是否營業','注意與前後點位是否順路']}
function enrich(p){const x=EXTRA[p.id]||{};return{...p,markerEmoji:x.emoji||CATEGORY_EMOJI[p.p]||'📍',site:x.site||'',siteLabel:x.siteLabel||'官方／參考頁',highlights:x.highlights||getDefaultHighlights(p)}}
function thumb(p){const m={pikmin:['#dcfce7','#22c55e'],jjk:['#ede9fe','#8b5cf6'],conan:['#dbeafe','#2563eb'],literary:['#fef3c7','#f59e0b'],food:['#fee2e2','#ef4444'],hotel:['#e5e7eb','#4b5563']};const c=m[p.p]||['#e5e7eb','#94a3b8'];const t=p.n.replace(/&/g,'＆').slice(0,20),s=p.a.replace(/&/g,'＆').slice(0,24);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="280" viewBox="0 0 600 280"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c[0]}"/><stop offset="100%" stop-color="${c[1]}"/></linearGradient></defs><rect rx="26" ry="26" width="600" height="280" fill="url(#g)"/><circle cx="520" cy="70" r="78" fill="rgba(255,255,255,.2)"/><text x="64" y="118" font-size="78">${p.markerEmoji}</text><text x="64" y="182" font-size="34" font-weight="700" fill="#111827">${t}</text><text x="64" y="224" font-size="22" fill="#374151">${s}</text></svg>`;return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function popup(raw){const p=enrich(raw);const site=p.site?`<a class="mini" href="${p.site}" target="_blank" rel="noopener">${p.siteLabel}</a>`:'';const src=p.ref?`<a class="mini" href="${p.ref}" target="_blank" rel="noopener">場景來源</a>`:'';return `<div class="popup-wrap"><img class="popup-thumb" src="${thumb(p)}" alt="${p.n} 縮圖"><div class="popup-title">${p.markerEmoji} ${p.n}</div><div class="popup-meta">${p.a}｜${D.labels[p.p]}</div><div class="popup-mini">${p.m}</div><div class="popup-links"><a class="mini" href="${gm(p)}" target="_blank" rel="noopener">Google Maps</a><a class="mini" href="${osm(p)}" target="_blank" rel="noopener">OpenStreetMap</a>${site}${src}</div></div>`}
const map=L.map('map');
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const markers=[];const lines=[];
const gm=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.n+' '+p.a);
const osm=p=>'https://www.openstreetmap.org/?mlat='+p.lat+'&mlon='+p.lng+'#map=16/'+p.lat+'/'+p.lng;
const routeDir=r=>{const a=byId[r.f],b=byId[r.t];return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a.n)+'&destination='+encodeURIComponent(b.n)};
const routeGroups=v=>({all:['arrival','day1','day2','food','transfer','osaka_conan','return'],arrival:['arrival'],day1:['day1','food'],day2:['day2'],transfer:['transfer','osaka_conan'],osaka_conan:['osaka_conan'],return:['return'],pikmin:['day1','day2'],food:['food'],hotels:['arrival','transfer','return']})[v]||['arrival','day1','day2','food','transfer','osaka_conan','return'];
D.points.forEach((raw,i)=>{const p=enrich({...raw,num:i+1});const icon=L.divIcon({className:'',html:`<div class="marker-shell ${p.p}"><span class="marker-emoji">${p.markerEmoji}</span><span class="marker-badge">${i+1}</span></div>`,iconSize:[40,40],iconAnchor:[20,20]});const marker=L.marker([p.lat,p.lng],{icon}).addTo(map).bindPopup(popup(p));marker._view=p.v||[];marker._type=p.p;markerById[p.id]=marker;marker.on('click',()=>document.getElementById('c_'+p.id)?.scrollIntoView({behavior:'smooth',block:'center'}));markers.push(marker)});
D.routes.forEach(r=>{const a=byId[r.f],b=byId[r.t];const line=L.polyline([[a.lat,a.lng],[b.lat,b.lng]],{color:ROUTE_COLOR[r.g]||'#94a3b8',weight:['food','return'].includes(r.g)?3:4,opacity:.82,dashArray:['food','return'].includes(r.g)?'6,8':null}).addTo(map);line._group=r.g;lines.push(line)});
map.fitBounds(L.featureGroup(markers).getBounds().pad(.12));
const filters=document.getElementById('filters');
D.views.forEach(([k,l],i)=>{const b=document.createElement('button');b.className='fbtn'+(i===0?' active':'');b.textContent=l;b.dataset.view=k;b.onclick=()=>applyView(k,b);filters.appendChild(b)});
const board=document.getElementById('board');
D.itinerary.forEach(day=>{const el=document.createElement('article');el.className='day-card';el.innerHTML=`<div class="day-top"><div><div class="day-no">${day.day}</div><div class="day-date">${day.date}</div></div><span class="pace">${day.pace}</span></div><div class="day-theme">${day.title}</div><div class="day-base">${day.base}</div><div class="tag-row">${day.tags.map(([k,t])=>`<span class="tag ${k}">${t}</span>`).join('')}</div><div class="quick-list">${day.focus.map(([t,d])=>`<div class="quick-item"><b>${t}</b><span>${d}</span></div>`).join('')}</div><div class="mini-row"><button class="jump-btn" data-view="${day.key}">看這天地圖</button></div>`;board.appendChild(el)});
const routeList=document.getElementById('routeList');
D.routes.forEach(r=>{const a=byId[r.f],b=byId[r.t],el=document.createElement('div');el.className='routeItem';el.dataset.group=r.g;el.innerHTML=`<b>${a.n} → ${b.n}</b><div class="muted">${r.m}｜${r.tm}</div><div class="actions"><a class="mini" href="${routeDir(r)}" target="_blank" rel="noopener">Google 路線</a></div>`;routeList.appendChild(el)});
const sideEyebrow=document.querySelector('.side .eyebrow');
const sideTitle=document.querySelector('.side h2');
const sideStack=document.querySelector('.side .stack');
sideStack.innerHTML=`<div class="sequence-shell"><div class="sequence-panel" id="sequenceSummaryPanel"></div><div class="sequence-panel" id="sequenceHighlightPanel"></div><div class="sequence-scroll" id="sequenceScroll"></div></div>`;
const sequenceSummaryPanel=document.getElementById('sequenceSummaryPanel');
const sequenceHighlightPanel=document.getElementById('sequenceHighlightPanel');
const sequenceScroll=document.getElementById('sequenceScroll');
const cardsWrap=document.getElementById('cards');
const cardFilterBar=document.createElement('div');cardFilterBar.className='card-filter-bar';cardFilterBar.id='cardFilterBar';cardsWrap.parentNode.insertBefore(cardFilterBar,cardsWrap);
['all','pikmin','jjk','conan','literary','food','hotel'].forEach((type,idx)=>{const btn=document.createElement('button');btn.className='card-chip'+(idx===0?' active':'');btn.textContent=CATEGORY_LABELS[type];btn.dataset.type=type;btn.onclick=()=>applyCardType(type,btn);cardFilterBar.appendChild(btn)});
const cards=[];
D.points.forEach((raw,i)=>{const p=enrich(raw),site=p.site?`<a class="mini" href="${p.site}" target="_blank" rel="noopener">${p.siteLabel}</a>`:'',src=p.ref?`<a class="mini" href="${p.ref}" target="_blank" rel="noopener">場景來源</a>`:'',el=document.createElement('article');el.className='card';el.id='c_'+p.id;el.dataset.views=(p.v||[]).join(' ');el.dataset.type=p.p;el.innerHTML=`<div class="head"><div class="num ${p.p}">${p.markerEmoji}</div><div><div class="card-title-row"><h3>${p.n}</h3><span class="spot-index">#${i+1}</span></div><div class="meta">${p.a}｜${D.labels[p.p]}｜建議停留：${p.s}</div></div></div><div class="sum">${p.m}</div><div class="highlight-box"><div class="highlight-title">必看／檢視重點</div><ul class="highlight-list">${p.highlights.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="actions"><a class="mini" href="${gm(p)}" target="_blank" rel="noopener">Google Maps</a><a class="mini" href="${osm(p)}" target="_blank" rel="noopener">OpenStreetMap</a>${site}${src}</div>`;cardsWrap.appendChild(el);cards.push(el)});
function renderSideHeader(view){if(view==='all'){sideEyebrow.textContent='Trip overview';sideTitle.textContent='每日行程順序與重點';sequenceSummaryPanel.innerHTML='<div class="sequence-panel-title">行程摘要</div><div class="sequence-panel-text">目前顯示全旅程版本。切換到某一天後，右側會改成該日的專屬摘要、Highlight 與順序景點。</div>';sequenceHighlightPanel.innerHTML='<div class="sequence-panel-title">Highlight</div><ul class="sequence-highlight-list"><li>Pikmin 主線以 Day 2、Day 3 為主。</li><li>動漫補線集中在京都東山與大阪城周邊。</li><li>點右側景點，左邊地圖會自動把該點置中並打開資訊。</li></ul>';return;}const itinerary=D.itinerary.find(x=>x.key===view);if(!itinerary){sideEyebrow.textContent='Trip panel';sideTitle.textContent='行程順序';return;}sideEyebrow.textContent=itinerary.day+' itinerary';sideTitle.textContent=itinerary.title;const summaryText=(itinerary.focus||[]).slice(0,2).map(x=>x[1]).join(' ');sequenceSummaryPanel.innerHTML=`<div class="sequence-panel-title">本日摘要</div><div class="sequence-panel-text">${summaryText||itinerary.base}</div>`;sequenceHighlightPanel.innerHTML=`<div class="sequence-panel-title">本日 Highlight</div><ul class="sequence-highlight-list">${(itinerary.focus||[]).map(x=>`<li><b>${x[0]}</b>：${x[1]}</li>`).join('')}</ul>`;}
function renderSequence(view){const keys=view==='all'?['arrival','day1','day2','transfer','return']:DAY_SEQUENCE[view]?[view]:[];if(!keys.length){sequenceScroll.innerHTML='<div class="sequence-panel"><div class="sequence-panel-text">這個篩選沒有對應的當天順序景點，請切換到某一天來看。</div></div>';return;}sequenceScroll.innerHTML=keys.map(key=>{const itinerary=D.itinerary.find(x=>x.key===key);const items=(DAY_SEQUENCE[key]||[]).map((item,idx)=>{if(item.custom){return `<div>${idx>0?`<div class="sequence-gap">${item.move||''}</div>`:''}<div class="sequence-item"><div class="sequence-head"><div class="sequence-emoji">${item.emoji}</div><div><div class="sequence-title">${idx+1}. ${item.name}</div><div class="sequence-meta">${item.area}</div><div class="sequence-summary">${item.summary}</div></div></div></div></div>`;}const p=enrich(byId[item.id]);return `<div>${idx>0?`<div class="sequence-gap">${item.move||''}</div>`:''}<div class="sequence-item" data-spot-id="${p.id}"><div class="sequence-head"><div class="sequence-emoji">${p.markerEmoji}</div><div><div class="sequence-title">${idx+1}. ${p.n}</div><div class="sequence-meta">${p.a}</div><div class="sequence-summary">${p.m}</div></div></div></div></div>`;}).join('');return `<div class="sequence-group"><div class="sequence-day">${itinerary?`${itinerary.day}｜${itinerary.title}`:key}</div>${items}</div>`;}).join('');}
function setBoard(view){document.querySelectorAll('.jump-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));}
function applyCardType(type,btn){currentCardType=type;document.querySelectorAll('.card-chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderCards();}
function renderCards(){cards.forEach(card=>{const viewOk=currentView==='all'||card.dataset.views.split(' ').includes(currentView);const typeOk=currentCardType==='all'||card.dataset.type===currentCardType;card.classList.toggle('hidden',!(viewOk&&typeOk));});}
function centerSpotOnMap(spotId){const p=byId[spotId];const marker=markerById[spotId];if(!p||!marker)return;const targetZoom=Math.max(map.getZoom(),16);map.setView([p.lat,p.lng],targetZoom,{animate:true});setTimeout(()=>marker.openPopup(),180);document.getElementById('c_'+spotId)?.scrollIntoView({behavior:'smooth',block:'center'});}
function applyView(view,btn=null){currentView=view;document.querySelectorAll('.fbtn').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const groups=routeGroups(view);markers.forEach(m=>{const show=view==='all'||(m._view||[]).includes(view);if(show){if(!map.hasLayer(m))m.addTo(map)}else{if(map.hasLayer(m))map.removeLayer(m)}});lines.forEach(l=>{const show=groups.includes(l._group);if(show){if(!map.hasLayer(l))l.addTo(map)}else{if(map.hasLayer(l))map.removeLayer(l)}});document.querySelectorAll('.routeItem').forEach(r=>r.classList.toggle('hidden',!groups.includes(r.dataset.group)));setBoard(view);renderSideHeader(view);renderSequence(view);renderCards();}
document.addEventListener('click',e=>{const btn=e.target.closest('.jump-btn');if(btn){const view=btn.dataset.view;const filterBtn=document.querySelector(`.fbtn[data-view="${view}"]`);applyView(view,filterBtn);document.getElementById('map').scrollIntoView({behavior:'smooth',block:'start'});return;}const seq=e.target.closest('.sequence-item[data-spot-id]');if(seq){centerSpotOnMap(seq.dataset.spotId);}});
applyView('all',document.querySelector('.fbtn'));